doctrine:
    dbal:
        # configure these for your database server
        dbname:               '%env(resolve:DB_NAME)%'
        host:                 '%env(resolve:DB_HOST)%'
        port:                 '%env(resolve:DB_PORT)%'
        user:                 '%env(resolve:DB_USER)%'
        password:             '%env(resolve:DB_PASSWORD)%'
        driver:               '%env(resolve:DB_DRIVER)%'
        #server_version: '4.8'
        charset: '%env(resolve:DB_CHARSET)%'
        default_table_options:
            charset: '%env(resolve:DB_CHARSET)%'
            collate: '%env(resolve:DB_CHARSET_COLLATE)%'

        #url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App