Mutation:
    type: "object"
    config:
        fields:
            NewTodo:
                type: "Todo!"
                args:
                    todo:
                        type: "TodoInput!"
                resolve: "@=mutation('NewTodo', [args])"