TodoInput:
    type: input-object
    config:
        fields:
            title:
                type: 'String!'
            deadline:
                type: 'String!'
            description:
                type: 'String!'
            priority:
                type: 'Int!'